import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { buttonVariants } from '@/components/ui/button'
import Image from 'next/image'
import Link from 'next/link'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode

}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-black h-screen w-screen flex">
          <div className="m-auto w-4/12">
            {children}
          </div>
        </div>
    </body>
    </html >
  )
}
